### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by jinfagang** [mitesh77/Best-Flutter-UI-Templates#2]
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
#0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:73:7)
#1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
#2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
#3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
<asynchronous suspension>                            
```

**Comment by invisgoth** [comment]
Hello there is an error in your code. Your are calling something before the app is running.  Share your code for get more help

**Comment by mitesh77** [comment]
re-created project in flutter 1.9, check new changes. and reclone the project please and check it. (it's run completely fine).

**Comment by jinfagang** [comment]
@mitesh77  Thanks. I'll try. @invisgoth  I am just cloned this repo and running this repo itself...

**Comment by mitesh77** [comment]
It's working fine or some issues?

**Comment by jinfagang** [comment]
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
#0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:73:7)
#1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
#2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
#3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
<asynchronous suspension>
#4      OptionalMethodChannel.invokeMethod (pack<…>
```

Same error, I am flutter 1.9.1 (just upgrade yesterday every new)

**Comment by jinfagang** [comment]
I pulled just now.
